#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Call clang-format script

GIT_DIR=$(git rev-parse --git-dir)
$GIT_DIR/hooks/scripts/format_clang.sh

if [ $? -ne 0 ]; then
    printf "Format check failed.\n \
      Warning. If you want to skip format checking, run git commit --no-verify. \n"
 exit 1
fi
